CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE IF EXISTS games
    ADD COLUMN IF NOT EXISTS min_players INTEGER NOT NULL DEFAULT 2;

ALTER TABLE IF EXISTS sessions
    ADD COLUMN IF NOT EXISTS user_id BIGINT;
