// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func GameView(gameID string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"hero\"><span class=\"tag\">Game Lobby</span><h1>Gather your players</h1><p>Share the join code below so everyone can jump in.</p></header><section class=\"panel\"><div><h2>Join code</h2><p id=\"joinCode\" class=\"join-code\">Loading...</p></div><div class=\"status\"><span class=\"label\">Status</span><p id=\"gameStatus\">Loading...</p><button type=\"button\" id=\"startGame\" class=\"primary\">Start game</button> <button type=\"button\" id=\"endGame\" class=\"secondary\">End game</button></div></section><section class=\"panel\"><div><h2>Players</h2><p>Waiting for everyone to arrive.</p></div><ul id=\"playerList\" class=\"player-list\"></ul></section><section class=\"panel settings-panel\"><div><h2>Lobby settings</h2><p id=\"lobbyStatus\">Loading lobby settings...</p></div><form id=\"settingsForm\" class=\"settings-form\"><label><span class=\"label\">Rounds</span> <input id=\"roundsInput\" name=\"rounds\" type=\"number\" min=\"1\" max=\"10\" required></label> <label><span class=\"label\">Max players (0 = unlimited)</span> <input id=\"maxPlayersInput\" name=\"max_players\" type=\"number\" min=\"0\" max=\"12\" required></label> <label><span class=\"label\">Prompt pack</span> <select id=\"promptCategory\"></select></label> <label class=\"checkbox\"><input id=\"lobbyLocked\" name=\"lobby_locked\" type=\"checkbox\"> <span>Lock lobby to new players</span></label><div class=\"settings-actions\"><button type=\"submit\" class=\"secondary\">Save settings</button> <span id=\"settingsStatus\" class=\"result\"></span></div></form></section><p id=\"gameError\" class=\"result error\"></p><div id=\"gameMeta\" data-game-id=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(gameID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/game.templ`, Line: 62, Col: 42}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Picture This | Lobby", "/static/game.js", "").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
